name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Copy environment files
        run: |
          cp src/environments/environment.example.ts src/environments/environment.ts
          cp src/environments/environment.prod.example.ts src/environments/environment.prod.ts

      - name: Inject secrets into environment files
        run: |
          echo "export const environment = { production: false, apiUrl: '${{ secrets.API_URL }}' };" > src/environments/environment.ts
          echo "export const environment = { production: true, apiUrl: '${{ secrets.API_URL }}' };" > src/environments/environment.prod.ts

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test
